import { Atleta, MembroDirecao, Patrocinador } from '@/lib/managementTypes';

export const initialDirecao: MembroDirecao[] = [
    {
        id: 'dir-1',
        nome: 'Carlos Guimarães',
        cargo: 'Treinador',
        telefone: '',
        email: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dir-2',
        nome: 'João Oliveira',
        cargo: 'Diretor',
        telefone: '',
        email: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dir-3',
        nome: 'Paulo Benjamim',
        cargo: 'Diretor',
        telefone: '',
        email: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dir-4',
        nome: 'Fernando Pimentel',
        cargo: 'Diretor',
        telefone: '',
        email: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dir-5',
        nome: 'Paulo Correia',
        cargo: 'Preparador Físico',
        telefone: '',
        email: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const initialAtletas: Atleta[] = [
    // --- SENIORES ---
    // Guarda-Redes
    { id: 'atl-s-1', nome: 'Nuno Teixeira', escalao: 'seniores', dataNascimento: '1990-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-2', nome: 'Simão Loureiro', escalao: 'seniores', dataNascimento: '1990-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    // Jogadores
    { id: 'atl-s-4', nome: 'Tiago Pimentel', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-5', nome: 'Alexandre Resendes', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-6', nome: 'Vicente Correia', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-7', nome: 'Alexandre Ornelas', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-8', nome: 'Miguel Pimentel', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-9', nome: 'Carlos Guimarães', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-10', nome: 'Tiago Leite', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-11', nome: 'Pedro Paula', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-s-12', nome: 'Francisco Freitas', escalao: 'seniores', dataNascimento: '1995-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },

    // --- SUB 11 ---
    { id: 'atl-11-1', nome: 'Jonas Oliveira', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-11-2', nome: 'Joana Lourenço', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-11-3', nome: 'João Barroso', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-11-4', nome: 'Nuno Massa', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-11-5', nome: 'Leandro Rodrigues', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-11-6', nome: 'Rafael Malheiro', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-11-7', nome: 'Tiago Pereira', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-11-8', nome: 'José Vieira', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-11-9', nome: 'Vasco Lourenço', escalao: 'sub11', dataNascimento: '2015-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },

    // --- SUB 13 ---
    { id: 'atl-13-1', nome: 'Santiago Sousa', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-13-2', nome: 'Pedro Pacheco', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-13-3', nome: 'Santiago Resendes', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-13-4', nome: 'Salvador Resendes', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-13-5', nome: 'João Dias', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-13-6', nome: 'Guilherme Tavares', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-13-7', nome: 'Núria Faria', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-13-8', nome: 'Simão Melo', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-13-9', nome: 'Lourenço Áspera', escalao: 'sub13', dataNascimento: '2013-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },

    // --- SUB 17 ---
    { id: 'atl-17-1', nome: 'Rafael Rocha', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-2', nome: 'João Albuquerque', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-3', nome: 'Gil Ribeiro', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-4', nome: 'Gonçalo Mendonça', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-5', nome: 'Gustavo Cordeiro', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-6', nome: 'Benjamim Castanheira', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-7', nome: 'Miguel Silva', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-8', nome: 'Pedro Massa', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-9', nome: 'Gonçalo Cordovil', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-10', nome: 'Carolina Benjamim', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-11', nome: 'Kelly Silvestre', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-12', nome: 'David Oliveira', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-13', nome: 'Ana Benjamim', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-14', nome: 'Marco Pacheco', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: 'atl-17-15', nome: 'Rodrigo Cachapa', escalao: 'sub17', dataNascimento: '2009-01-01', telefone: '', email: '', morada: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];

export const initialPatrocinadores: Patrocinador[] = [
    {
        id: 'sp-1',
        nome: 'Azemad',
        logotipo: '/uploads/AzemadLogo.jpg',
        website: 'https://azemad.com/',
        contribuicao: 1500,
        dataInicio: '2025-01-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sp-2',
        nome: 'Auto Cordeiro',
        logotipo: '/uploads/AutoCordeiroLogo1.png',
        website: 'https://autocordeiro.com',
        contribuicao: 1200,
        dataInicio: '2025-01-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sp-3',
        nome: 'Crenku',
        logotipo: '/uploads/CrenkuLogo.png',
        website: 'https://www.facebook.com/crenku/?locale=pt_PT',
        contribuicao: 800,
        dataInicio: '2025-01-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sp-4',
        nome: 'Catchawards',
        logotipo: '/uploads/catchawards.png',
        website: 'https://www.catchawardsportugal.pt/',
        contribuicao: 1000,
        dataInicio: '2025-01-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sp-5',
        nome: 'Agência Funerária Lindo',
        logotipo: '/uploads/FunerariaLindoLogo.jpg',
        website: 'https://www.facebook.com/funerarialindo/?locale=pt_PT',
        contribuicao: 600,
        dataInicio: '2025-01-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];
